stellaris/urls.py
from django.urls import path
from stellaris import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "stellaris"

urlpatterns = [
    path('', views.HomeView, name="home"),
    path('category/', views.CategoryView, name="categories"),
    path('category/<str:slug>', views.MenuView, name="menu"),
    path('gallery/', views.GalleryView, name="gallery"),
    path('location/', views.LocationView, name="location"),
    path('party_category/', views.PartyCategoryView, name="party_category"),
    path('party_category/<str:slug>', views.PartyMenuView, name="party_menu"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stellaris_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("stellaris.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stellaris/models.py
from django.db import models


# Create your models here.


class Category(models.Model):
    slug = models.CharField(max_length=150, null=False, blank=False)
    name = models.CharField(max_length=150, null=False, blank=False)
    image = models.ImageField(upload_to='images/category')
    description = models.TextField(max_length=500, null=False, blank=False)
    availability = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.CharField(max_length=150, null=False, blank=False)
    name = models.CharField(max_length=150, null=False, blank=False)
    product_image = models.ImageField(upload_to='images/foods')
    description = models.CharField(max_length=250, null=False, blank=False)
    price = models.FloatField(null=False,blank=False)
    availability = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Gallery(models.Model):
    description = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='images/gallery')  
    date_taken = models.DateField(auto_now_add=False,auto_now=False)

    def __str__(self):
        return self.description
    
    class Meta:
        verbose_name_plural = "Gallery"
        get_latest_by = 'date_taken'

class PartyTraysCategory(models.Model):
    slug = models.CharField(max_length=150, null=False, blank=False)
    name = models.CharField(max_length=150, null=False, blank=False)
    image = models.ImageField(upload_to='images/category')
    description = models.TextField(max_length=500, null=False, blank=False)
    availability = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Party Trays Category"

class PartyTraysProduct(models.Model):
    category = models.ForeignKey(PartyTraysCategory, on_delete=models.CASCADE)
    slug = models.CharField(max_length=150, null=False, blank=False)
    name = models.CharField(max_length=150, null=False, blank=False)
    product_image = models.ImageField(upload_to='images/foods')
    description = models.CharField(max_length=250, null=False, blank=False)
    price = models.FloatField(null=False,blank=False)
    availability = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Party Trays Product"

class Reservation(models.Model):
    first_name = models.CharField(max_length=50,blank=False)
    last_name = models.CharField(max_length=30,blank=False)
    address = models.CharField(max_length=150,default="Catabangan Zamboanga City")
    phone_number = models.CharField(max_length=11,blank=False)
    email = models.EmailField(max_length=80,blank=False)
    pax = models.PositiveIntegerField(default=15,null=False)
    event_type = models.CharField(max_length=50,blank=False)
    event_date = models.DateField()
    time_start = models.TimeField()
    time_end = models.TimeField()
    remarks = models.TextField(max_length=500,null=False,blank=True)
    status = models.BooleanField(default=False)

stellaris/views.py
from math import prod
from multiprocessing import context
from unicodedata import category
from django.shortcuts import render
from .models import *

# Create your views here.
def HomeView(request):
    news = Gallery.objects.all().order_by("-date_taken")[:3]
    context = {
        'news':news
    }
    return render (request, 'home.html', context)

def CategoryView(request):
    category = Category.objects.filter(availability=True)
    context = {
        'category':category
    }
    return render (request, 'category.html', context)

def MenuView(request, slug):
    if(Category.objects.filter(slug=slug, availability=True)):
        products = Product.objects.filter(category__slug=slug,availability=True)
        category_name = Category.objects.filter(slug=slug).first()
        context = {
            'products':products,
            'category_name':category_name,
        }
        return render(request, 'menu.html', context)

def PartyCategoryView(request):
    party_category = PartyTraysCategory.objects.filter(availability=True, name__icontains='Tray')
    party_category_set = PartyTraysCategory.objects.filter(availability=True, name__icontains='Set')
    context = {
        'party_category':party_category,
        'party_category_set':party_category_set,
    }
    return render (request, 'partycategory.html', context)

def PartyMenuView(request, slug):
    if(PartyTraysCategory.objects.filter(slug=slug, availability=True)):
        party_products = PartyTraysProduct.objects.filter(category__slug=slug,availability=True)
        party_category_name = PartyTraysCategory.objects.filter(slug=slug).first()
        context = {
            'party_products':party_products,
            'party_category_name':party_category_name,
        }
        return render(request, 'partymenu.html', context)



def LocationView(request):
    return render(request, 'location.html')

def GalleryView(request):
    gallery = Gallery.objects.all().order_by("-date_taken")
    context = {
        'gallery':gallery
    }
    return render(request, 'gallery.html', context)

templates/category.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/214fab10ef.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/navbar/logo.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>Homepage</title>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: antiquewhite;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/navbar/indexlogo.png' %}" style="max-width: auto; max-height:50px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:categories' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Delivery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:party_category' %}">Reservation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:location' %}">Location</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:gallery' %}">Gallery</a>
              </li>
              </ul>
        </div>
    </div>
</nav>
<div class="container">
    <h2 class="text-center mb-3" style="color: black;">Menu Category</h2>
    <hr>
    <div class="row">
        {% for c in category %}
            <div class="col-sm-3">
                <div class="card mb-3" style="max-height: fit-content; overflow: auto;">
                
                    <img src="{{ c.image.url }}" style="height: 200px;">
                    <div class="card-body text-center">           
                        
                      <a href = "{% url 'stellaris:menu' c.slug %}">{{c.name}}</a>
                    </div>
                </div>
            </div>            
        {% endfor %}
      </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</head>
</html>

templates/gallery.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/214fab10ef.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/navbar/logo.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    <title>Homepage</title>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: antiquewhite;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/navbar/indexlogo.png' %}" style="max-width: auto; max-height:50px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:categories' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Delivery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:party_category' %}">Reservation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:location' %}">Location</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:gallery' %}">Gallery</a>
              </li>
              </ul>
        </div>
    </div>
</nav>
<br>
    <div class = "container">
    <h2 id="titletext" class="text-center mb-3">D'Vhine Treats Cafe & Restaurant Gallery</h2>
        <div class="row">
            {% for p in gallery %}
            <div class="col-sm-3">
                <div class="gallery">
                <div class="card m-3">
                    <img src="{{p.image.url}}" height="200px">
                </div>
            </div>
            </div>
            {% endfor %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</head>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/214fab10ef.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/navbar/logo.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Homepage</title>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: antiquewhite;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/navbar/indexlogo.png' %}" style="max-width: auto; max-height:50px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:categories' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Delivery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:party_category' %}">Reservation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:location' %}">Location</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:gallery' %}">Gallery</a>
              </li>
              </ul>
        </div>
    </div>
</nav>
<br>
<body>
    <div class ="container">
    <h2 id="titletext" class="text-center mb-3">D'Vhine Treats Cafe & Restaurant</h2>
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner" style="border-radius: 30px;">
          <div class="carousel-item active">
            <img src="{% static 'images/carousel/car1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/carousel/car2.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/carousel/car3.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <br>
    <p id="intro" class="text-center mb-3">D’Vhine Treats Café and Restaurant Establish an <br> amazing place with a nice ambiance, fresh air, appetizing <br> food and nice view of the city. Relaxing and comfortable <br> place to hang out with your partner, family and friends. <br> Good place to escape the city hustle and bustle.</p>
    <br>
    <h3 class="text-center mb-3">What's New? <i class="fa-solid fa-rss"></i> </h3>
    <div class="row">
        {% for p in news %}
            <div class="col-sm-4">
                <div class="card mb-4" style="height: fit-content; overflow: auto; border-radius: 30px;">
                  <img src="{{ p.image.url }}" style="height: 195px;">
                  <p class="text-center mb-1">{{ p.description }}</p>
                  <div class="card-footer text-center">
                    <small class="text-muted">Last updated on: {{ p.date_taken}}</small>
                  </div>
                </div>
            </div>            
        {% endfor %}
      </div>
    <br>
    <h3 class="text-center mb-3">Where? <i class="fa-solid fa-location-dot"></i> </h3>
    <div class="ratio ratio-21x9">
        <iframe width="964" height="542" src="https://www.youtube.com/embed/CM4CkVFmTds" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="border-radius: 30px;"></iframe>
      </div>
    <br>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>

templates/location.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/214fab10ef.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/navbar/logo.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/location.css' %}">
    <title>Homepage</title>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: antiquewhite;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/navbar/indexlogo.png' %}" style="max-width: auto; max-height:50px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:categories' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Delivery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:party_category' %}">Reservation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:location' %}">Location</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:gallery' %}">Gallery</a>
              </li>
              </ul>
        </div>
    </div>
</nav>
<div class="container">
  <div class= "divmap">
    <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.400790384315!2d122.04389576533036!3d6.9619576481354715!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x325041119b92f6e5%3A0x82d93201a3093541!2sD&#39;Vhine%20treats!5e0!3m2!1sen!2sph!4v1643795550282!5m2!1sen!2sph" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy">
    </iframe>
    </div>
    <section class="about">
    <p class="text-center">Contact Us</p>
    <p class="text-center"><i class="fa-solid fa-phone"></i> 09368346373</p>
    <p class="text-center"><i class="fa-solid fa-envelope"></i> dvhinetreatscaferestaurant@gmail.com</p>
    <p class="text-center"><i class="fa-brands fa-chrome"></i> dvhinetreatscafe.com</p>
  </section>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</head>
</html>

templates/partycategory.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/214fab10ef.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/navbar/logo.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <title>Homepage</title>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: antiquewhite;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/navbar/indexlogo.png' %}" style="max-width: auto; max-height:50px;"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:categories' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Delivery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:party_category' %}">Reservation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:location' %}">Location</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'stellaris:gallery' %}">Gallery</a>
              </li>
              </ul>
        </div>
    </div>
</nav>
<div class="container">
    <h2 class="text-center mb-3" style="color: black;">Party Trays Category</h2>
    <h3 class="text-center mb-3" style="color: black;">For 15-20 Persons</h3>
    <hr>
    <div class="row">
        {% for c in party_category %}
            <div class="col-sm-3">
                <div class="card mb-3" style="max-height: fit-content; overflow: auto;">
                
                    <img src="{{ c.image.url }}" style="height: 200px;">
                    <div class="card-body text-center">           
                        
                      <a href = "{% url 'stellaris:party_menu' c.slug %}">{{c.name}}</a>
                    </div>
                </div>
            </div>            
        {% endfor %}
      </div>
      <br>
      <hr>
      <h2 class="text-center mb-3" style="color: black;">Party Set Category</h2>
      <h3 class="text-center mb-3" style="color: black;">For 15-20 Persons</h3>
      <br>
      <div class="row">
          {% for c in party_category_set %}
              <div class="col-sm-3">
                  <div class="card mb-3" style="max-height: fit-content; overflow: auto;">
                  
                      <img src="{{ c.image.url }}" style="height: 200px;">
                      <div class="card-body text-center">           
                          
                        <a href = "{% url 'stellaris:party_menu' c.slug %}">{{c.name}}</a>
                      </div>
                  </div>
              </div>            
          {% endfor %}
        </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</head>
</html>